import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Book Land Ethiopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: `
          try {
            const color = localStorage.getItem('primarycolor');
            if (color) {
              document.documentElement.style.setProperty('--primarycolor', color);
              
              // Darken color 20% for secondarycolor
              let num = parseInt(color.replace("#",""), 16);
              let R = (num >> 16) - 30;
              let G = ((num >> 8) & 0x00FF) - 30;
              let B = (num & 0x0000FF) - 30;
              
              R = R < 0 ? 0 : R;
              G = G < 0 ? 0 : G;
              B = B < 0 ? 0 : B;
              
              const secondary = "#" + (0x1000000 + R * 0x10000 + G * 0x100 + B).toString(16).slice(1);
              document.documentElement.style.setProperty('--secondarycolor', secondary);
            }

            const badge = localStorage.getItem('badgecolor');
            if (badge) {
              document.documentElement.style.setProperty('--badgecolor', badge);
            }

            const toastBg = localStorage.getItem('toastbgcolor');
            if (toastBg) {
              document.documentElement.style.setProperty('--toastbg', toastBg);
            }

            const toastText = localStorage.getItem('toasttextcolor');
            if (toastText) {
              document.documentElement.style.setProperty('--toasttext', toastText);
            }
          } catch (e) {}
        ` }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
